import { BeefShank, Chicken, ChickenFeet, Corn, Cucumber, Egg, Goji, Jellyfish, Lemon, Millet, MungBean, Mushroom, Peanut, Pork, Potato, PotherbMustard, PreservedEgg, Sesame, Shrimp, WoodEar } from './ingredients'
import { Item, ColdDish, CongeeDish, WheatenDish, NoodleDish, RiceDish, SoupDish, PorkDish, BeefDish, LambDish, ChickenDish, SeafoodDish, VegetableDish, StreetFoodDish, Drink, Dessert, DessertCake } from './menu_types'

export const menu: ReadonlyArray<Item> = [
  new CongeeDish('香菇鸡肉粥', 'Congee w/ Chicken & Mushrooms', [Chicken, Mushroom], ['Jaybase']),
  new CongeeDish('皮蛋瘦肉粥', 'Congee w/ Pork & Preserved Eggs', [Pork, PreservedEgg], ['Jaybase', 'Jerryc05']),
  new CongeeDish('雪菜肉丝粥', 'Congee w/ potherb mustard & shredded pork', [PotherbMustard, Pork], ['Jaybase']),
  new CongeeDish('八宝粥', 'Mixed Congee', undefined, ['Jaybase']),
  new CongeeDish('玉米碴子粥', 'Congee w/ Crushed Corn', [Corn, Goji], ['Jaybase']),
  new CongeeDish('小米粥', 'Millet Congee', [Millet, Goji], ['Jaybase']),
  new CongeeDish('白米粥', 'Rice Congee', [], ['Jaybase', 'Jerryc05']),
  new ColdDish('凉拌海蜇头', 'Jellyfish Head Salad', [Jellyfish], ['Jaybase', 'Jerryc05']),
  new ColdDish('凉拌黄瓜', 'Cucumber Salad', [Cucumber], ['Jaybase']),
  new ColdDish('拍黄瓜', 'Smashed Cucumber Salad', [Cucumber], ['Jaybase']),
  new ColdDish('油炸花生米', 'Fried Peanuts', [Peanut], ['Jaybase']),
  new ColdDish('五香牛肉', 'Multi Spiced Beef', [BeefShank], ['Jaybase']),
  new ColdDish('酱牛肉', 'Spiced Beef', [BeefShank], ['Jaybase', 'Jerryc05', 'Titi', 'Tuge']),
  new ColdDish('卤蛋', 'Marinated Egg', [Egg], ['Jaybase']),
  new ColdDish('酸辣虾', 'Sour & Spicy Shrimp', [Shrimp], ['Jaybase', 'Titi']),
  new ColdDish('酸辣鸡爪', 'Sour & Spicy Chicken Feet', [ChickenFeet], ['Jaybase', 'Wuge']),
  new ColdDish('凉拌土豆丝', 'Shredded Potato Salad', [Potato], ['Jaybase']),
  new ColdDish('酸辣土豆丝', 'Sour & Spicy Shredded Potato', [Potato], ['Jaybase']),
  new ColdDish('白糖西红柿', 'Sour & Spicy Shredded Potato', [Potato], ['Jaybase']),
  new ColdDish('凉拌木耳', 'Wood Ear Salad', [WoodEar], ['Jaybase']),
  new ColdDish('五彩拉皮', 'Wood Ear Salad', [WoodEar], ['Jerryc05']),
  new WheatenDish('馅饼（自选）', 'Pie (Customized Filling)', [], ['Jaybase']),
  new WheatenDish('油条', 'Fried Dough Fritter', [], ['Jaybase']),
  new WheatenDish('葱油饼', 'Scallion Crepe', [], ['Jaybase']),
  new WheatenDish('农家酱香饼', 'Soy Flavored Flatbread Crepe', [], ['Jaybase']),
  new WheatenDish('鸡蛋饼', 'Egg Crepe', [Egg], ['Jaybase', 'Jerryc05']),
  new WheatenDish('春饼', 'Spring Crepe', [], ['Jaybase']),
  new WheatenDish('麻酱红糖饼', 'Brown Sugar Crepe w/ Sesame Paste', [Sesame], ['Jaybase']),
  new WheatenDish('煎饺', 'Fried Dumpling', [], ['Jaybase']),
  new WheatenDish('水饺', 'Dumpling', [], ['Jaybase']),
  new WheatenDish('红油抄手', 'Spicy Wonton in Chili Oil', undefined, ['Jaybase']),
  new WheatenDish('云吞', 'Wonton', undefined, ['Jaybase']),
  new WheatenDish('韭菜盒子', 'Fried Chinese Chives Pocket', undefined, ['Jaybase']),
  new WheatenDish('海鲜煎饼', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new NoodleDish('香菇鸡肉面', undefined, undefined, ['Jaybase']),
  new NoodleDish('红烧牛肉面', undefined, undefined, ['Jaybase']),
  new NoodleDish('重庆小面', undefined, undefined, ['Jaybase']),
  new NoodleDish('榨菜肉丝面', undefined, undefined, ['Jaybase']),
  new NoodleDish('雪菜肉丝面', undefined, undefined, ['Jaybase']),
  new NoodleDish('鸡汤面', undefined, undefined, ['Jaybase']),
  new NoodleDish('麻酱拌面', undefined, undefined, ['Jaybase']),
  new NoodleDish('鸡丝凉面', undefined, undefined, ['Jaybase']),
  new NoodleDish('大排面', undefined, undefined, ['Jaybase']),
  new NoodleDish('炒面', undefined, undefined, ['Jaybase']),
  new NoodleDish('炸酱面', undefined, undefined, ['Jaybase']),
  new NoodleDish('打卤面', undefined, undefined, ['Jaybase']),
  new NoodleDish('番茄鸡蛋面', undefined, undefined, ['Jaybase']),
  new NoodleDish('什锦面', undefined, undefined, ['Jaybase']),
  new NoodleDish('芸豆焖面', undefined, undefined, ['Jaybase']),
  new NoodleDish('意大利肉酱面', undefined, undefined, ['Jaybase']),
  new NoodleDish('番茄肥牛面', undefined, undefined, ['Jaybase']),
  new NoodleDish('阳春面', undefined, undefined, ['Jaybase']),
  new NoodleDish('油泼面', undefined, undefined, ['Jaybase']),
  new NoodleDish('冷面', undefined, undefined, ['Jaybase']),
  new NoodleDish('烤冷面', undefined, undefined, ['Jaybase']),
  new NoodleDish('日本拉面', undefined, undefined, ['Jaybase']),
  new NoodleDish('虾仁奶油意面', undefined, undefined, ['Jerryc05']),
  new NoodleDish('番茄肉酱意面', undefined, undefined, ['Jerryc05', 'Titi']),
  new NoodleDish('青椒牛柳意面', undefined, undefined, ['Jerryc05', 'Titi']),
  new RiceDish('卤肉饭', undefined, undefined, ['Jaybase']),
  new RiceDish('照烧鸡肉饭', undefined, undefined, ['Jaybase']),
  new RiceDish('照烧牛肉饭', undefined, undefined, ['Jaybase']),
  new RiceDish('蛋炒饭', undefined, undefined, ['Jaybase']),
  new RiceDish('盖浇饭', undefined, undefined, ['Jaybase']),
  new RiceDish('煲仔饭', undefined, undefined, ['Jaybase']),
  new RiceDish('小龙虾盖饭', undefined, undefined, ['Jaybase']),
  new RiceDish('日式牛丼饭', undefined, undefined, []),
  new RiceDish('不放一滴油の日式滑蛋猪排饭', undefined, undefined, ['Jerryc05']),
  new RiceDish('茄汁芝士焗饭', undefined, undefined, ['Jerryc05']),
  new RiceDish('海鲜糯米鸡', undefined, undefined, ['Jerryc05']),
  new RiceDish('三角烤饭团', undefined, undefined, ['Jerryc05']),
  new RiceDish('午餐肉烤饭团', undefined, undefined, ['Jerryc05']),
  new RiceDish('卤猪脚饭', undefined, undefined, ['Jerryc05']),
  new RiceDish('猪油拌饭', undefined, undefined, ['Jerryc05']),
  new PorkDish('小酥肉', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new PorkDish('干炸里脊', undefined, undefined, ['Jaybase']),
  new PorkDish('糖醋里脊', undefined, undefined, ['Jaybase']),
  new PorkDish('锅包肉', undefined, undefined, ['Jaybase']),
  new PorkDish('溜肉段', undefined, undefined, ['Jaybase']),
  new PorkDish('芸豆土豆炖排骨', undefined, undefined, ['Jaybase']),
  new PorkDish('糖醋排骨', undefined, undefined, ['Jaybase']),
  new PorkDish('豆豉排骨', undefined, undefined, ['Jaybase']),
  new PorkDish('酱排骨', undefined, undefined, ['Jerryc05']),
  new PorkDish('避风塘排骨', undefined, undefined, ['Jaybase']),
  new PorkDish('蒜香排骨', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new PorkDish('腐乳排骨', undefined, undefined, []),
  new PorkDish('鱼香肉丝', undefined, undefined, ['Jaybase']),
  new PorkDish('京酱肉丝', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new PorkDish('青椒肉丝', undefined, undefined, ['Jaybase']),
  new PorkDish('水煮肉片', undefined, undefined, ['Jaybase']),
  new PorkDish('木须肉', undefined, undefined, ['Jaybase']),
  new PorkDish('洋葱炒肉', undefined, undefined, ['Jaybase']),
  new PorkDish('红烧肉', undefined, undefined, ['Jaybase']),
  new PorkDish('梅菜扣肉', undefined, undefined, ['Jerryc05']),
  new PorkDish('韩式辣白菜炒肉', undefined, undefined, ['Jaybase']),
  new PorkDish('烤猪蹄', undefined, undefined, ['Jaybase']),
  new PorkDish('炸猪蹄', undefined, undefined, ['Jaybase']),
  new PorkDish('红烧猪蹄', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new PorkDish('黄豆焖猪蹄', undefined, undefined, []),
  new PorkDish('酱猪肘', undefined, undefined, ['Jerryc05']),
  new PorkDish('烤猪肉串', undefined, undefined, ['Jaybase']),
  new PorkDish('烤五花肉', undefined, undefined, ['Jaybase']),
  new PorkDish('咖喱猪排饭', undefined, undefined, ['Jaybase']),
  new PorkDish('红烧狮子头', undefined, undefined, ['Jaybase']),
  new PorkDish('蒸排骨', undefined, undefined, []),
  new PorkDish('豆瓣炖排骨', undefined, undefined, []),
  new PorkDish('肉末麻婆豆腐', undefined, undefined, ['Jerryc05']),
  new PorkDish('辣椒炒肉', undefined, undefined, ['Jerryc05']),
  new PorkDish('脆皮猪五花', undefined, undefined, []),
  new PorkDish('回锅肉', undefined, undefined, ['Jerryc05']),
  new PorkDish('粉蒸肉', undefined, undefined, ['Jerryc05']),
  new PorkDish('粉蒸排骨', undefined, undefined, ['Jerryc05']),
  new PorkDish('照烧猪肉', undefined, undefined, ['Jerryc05']),
  new PorkDish('虎纠荔枝肉', undefined, undefined, ['Jerryc05']),
  new PorkDish('水煮肉片', undefined, undefined, ['Jerryc05']),
  new BeefDish('孜然牛肉', undefined, undefined, ['Jaybase']),
  new BeefDish('葱爆牛肉', undefined, undefined, ['Jaybase']),
  new BeefDish('酸汤肥牛', undefined, undefined, ['Jaybase']),
  new BeefDish('肥牛金针菇卷', undefined, undefined, ['Jaybase']),
  new BeefDish('煎牛排', undefined, undefined, ['Jaybase', 'Jerryc05', 'Tuge']),
  new BeefDish('烤牛排', undefined, undefined, ['Jaybase']),
  new BeefDish('烤牛肉串', undefined, undefined, ['Jaybase']),
  new BeefDish('红烧牛腩', undefined, undefined, ['Jerryc05']),
  new BeefDish('番茄牛腩', undefined, undefined, ['Jaybase']),
  new BeefDish('土豆烧牛腩', undefined, undefined, []),
  new BeefDish('咖喱牛肉', undefined, undefined, ['Jaybase']),
  new BeefDish('黑椒牛仔骨', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new BeefDish('杭椒牛柳', undefined, undefined, ['Jaybase']),
  new BeefDish('香菜炒牛百叶', undefined, undefined, ['Jaybase']),
  new BeefDish('黑椒牛肉粒', undefined, undefined, ['Jaybase']),
  new LambDish('孜然羊肉', undefined, undefined, ['Jaybase']),
  new LambDish('葱爆羊肉', undefined, undefined, ['Jaybase']),
  new LambDish('麻酱拌肥羊', undefined, undefined, ['Jaybase']),
  new LambDish('羊蝎子', undefined, undefined, ['Jaybase']),
  new LambDish('烤羊肉串', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new LambDish('鱼羊鲜', undefined, undefined, []),
  new LambDish('法式香煎小羊排', undefined, undefined, ['Jerryc05']),
  new ChickenDish('大盘鸡', undefined, undefined, ['Jaybase']),
  new ChickenDish('口水鸡', undefined, undefined, ['Jaybase']),
  new ChickenDish('炸鸡', undefined, undefined, ['Jaybase']),
  new ChickenDish('盐酥鸡', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new ChickenDish('鸡米花', undefined, undefined, ['Jaybase']),
  new ChickenDish('可乐鸡翅', undefined, undefined, ['Jaybase', 'Jerryc05', 'Tuge']),
  new ChickenDish('红烧鸡翅', undefined, undefined, ['Jaybase', 'Jerryc05', 'Tuge']),
  new ChickenDish('蒜香鸡翅', undefined, undefined, ['Jaybase']),
  new ChickenDish('橙香鸡翅', undefined, undefined, []),
  new ChickenDish('小鸡炖蘑菇', undefined, undefined, ['Jaybase']),
  new ChickenDish('地锅鸡', undefined, undefined, ['Jaybase']),
  new ChickenDish('烤鸡', undefined, undefined, ['Jaybase', 'Jerryc05', 'Titi', 'Wuge']),
  new ChickenDish('照烧鸡', undefined, undefined, ['Jaybase']),
  new ChickenDish('杏鲍菇炒鸡丁', undefined, undefined, ['Jaybase']),
  new ChickenDish('辣子鸡', undefined, undefined, ['Jaybase']),
  new ChickenDish('宫保鸡丁', undefined, undefined, ['Jaybase']),
  new ChickenDish('咖喱鸡', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new ChickenDish('炸鸡排', undefined, undefined, ['Jaybase']),
  new ChickenDish('爆浆鸡排', undefined, undefined, ['Jaybase']),
  new ChickenDish('炸鸡柳', undefined, undefined, ['Jaybase']),
  new ChickenDish('烤鸡胸', undefined, undefined, ['Jaybase']),
  new ChickenDish('黄焖鸡', undefined, undefined, ['Jerryc05', 'Tuge']),
  new ChickenDish('宫保鸡丁', undefined, undefined, ['Jerryc05', 'Tuge']),
  new SeafoodDish('红烧带鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('炸带鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('红烧鱼', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new SeafoodDish('松鼠桂鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('烤鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('红烧鲅鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('地锅鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('蒜蓉大虾', undefined, undefined, ['Jaybase']),
  new SeafoodDish('干烧大虾', undefined, undefined, ['Jaybase']),
  new SeafoodDish('凤尾大虾', undefined, undefined, ['Jaybase']),
  new SeafoodDish('油焖大虾', undefined, undefined, ['Jaybase', 'Jerryc05', 'Tuge', 'Wuge']),
  new SeafoodDish('葱烧海参', undefined, undefined, ['Jaybase']),
  new SeafoodDish('肉末海参', undefined, undefined, ['Jaybase']),
  new SeafoodDish('蒜蓉小海鲜', undefined, undefined, ['Jaybase']),
  new SeafoodDish('麻辣小龙虾', undefined, undefined, ['Jaybase']),
  new SeafoodDish('水煮海鲜', undefined, undefined, ['Jaybase']),
  new SeafoodDish('香辣蟹', undefined, undefined, ['Jaybase']),
  new SeafoodDish('辣炒蛤蜊', undefined, undefined, ['Jaybase']),
  new SeafoodDish('凉拌八爪鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('铁板鱿鱼', undefined, undefined, ['Jaybase']),
  new SeafoodDish('清蒸鲈鱼', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new SeafoodDish('西兰花炒虾仁', undefined, undefined, ['Jaybase']),
  new SeafoodDish('蒜蓉扇贝', undefined, undefined, ['Jaybase']),
  new SeafoodDish('红酒香煎三文鱼', undefined, undefined, ['Jerryc05']),
  new SeafoodDish('珍珠丸子', undefined, undefined, ['Jerryc05']),
  new SeafoodDish('麻辣香锅', undefined, undefined, ['Jerryc05', 'Tuge']),
  new SeafoodDish('鱼头泡饼', undefined, undefined, ['Jerryc05']),
  new SeafoodDish('黄油芝士虾', undefined, undefined, ['Jerryc05']),
  new SeafoodDish('炸虾天妇罗', undefined, undefined, ['Jerryc05']),
  new VegetableDish('醋溜白菜', undefined, undefined, ['Jaybase']),
  new VegetableDish('醋溜土豆丝', undefined, undefined, ['Jaybase']),
  new VegetableDish('酸辣土豆丝', undefined, undefined, ['Jaybase']),
  new VegetableDish('蒜蓉青菜', undefined, undefined, ['Jaybase']),
  new VegetableDish('上汤娃娃菜', undefined, undefined, ['Jaybase']),
  new VegetableDish('番茄炒鸡蛋', undefined, undefined, ['Jaybase']),
  new VegetableDish('冬瓜虾仁', undefined, undefined, ['Jaybase']),
  new VegetableDish('萝卜大虾', undefined, undefined, ['Jaybase']),
  new VegetableDish('茄盒', undefined, undefined, ['Jaybase']),
  new VegetableDish('藕盒', undefined, undefined, ['Jaybase']),
  new VegetableDish('肉末茄子', undefined, undefined, ['Jaybase']),
  new VegetableDish('鱼香茄子', undefined, undefined, ['Jaybase']),
  new VegetableDish('拔丝地瓜', undefined, undefined, ['Jaybase']),
  new VegetableDish('干煸豆角', undefined, undefined, ['Jaybase']),
  new VegetableDish('干煸大头菜', undefined, undefined, ['Jaybase']),
  new VegetableDish('蚝油生菜', undefined, undefined, ['Jaybase']),
  new VegetableDish('豆豉鲮鱼油麦菜', undefined, undefined, ['Jaybase']),
  new VegetableDish('干锅花菜', undefined, undefined, ['Jaybase']),
  new VegetableDish('干锅豆角', undefined, undefined, ['Jaybase']),
  new VegetableDish('干锅土豆片', undefined, undefined, ['Jaybase']),
  new VegetableDish('干锅豆腐', undefined, undefined, ['Jaybase']),
  new VegetableDish('包菜鱿鱼粉丝煲', undefined, undefined, ['Jerryc05']),
  new VegetableDish('蒜蓉西兰花', undefined, undefined, ['Jerryc05']),
  new VegetableDish('韭菜炒蛋', undefined, undefined, ['Jerryc05']),
  new VegetableDish('芹菜炒肉末', undefined, undefined, []),
  new VegetableDish('炒合菜', undefined, undefined, []),
  new VegetableDish('洋葱炒蛋', undefined, undefined, []),
  new VegetableDish('皮蛋擂青椒', undefined, undefined, ['Jerryc05']),
  new VegetableDish('素三鲜', undefined, undefined, ['Jerryc05']),
  new VegetableDish('龙吟鸡腿', undefined, undefined, ['Jerryc05']),
  new SoupDish('绿豆汤', 'Mung Bean Soup', [MungBean], ['Jaybase']),
  new SoupDish('紫菜蛋汤', undefined, undefined, ['Jaybase']),
  new SoupDish('番茄鸡蛋汤', undefined, undefined, ['Jaybase']),
  new SoupDish('排骨汤', undefined, undefined, ['Jaybase']),
  new SoupDish('鸡汤', undefined, undefined, ['Jaybase']),
  new SoupDish('清炖羊肉汤', undefined, undefined, ['Jaybase']),
  new SoupDish('鱼汤', undefined, undefined, ['Jaybase']),
  new SoupDish('番茄牛腩汤', undefined, undefined, ['Jaybase']),
  new SoupDish('牛尾汤', undefined, undefined, ['Jaybase']),
  new SoupDish('猪脚汤', undefined, undefined, ['Jaybase']),
  new SoupDish('鸡蛋蘑菇汤', undefined, undefined, ['Jaybase']),
  new SoupDish('平桥豆腐羹', undefined, undefined, ['Jaybase']),
  new SoupDish('西湖牛肉羹', undefined, undefined, ['Jerryc05']),
  new SoupDish('宋嫂鱼羹', undefined, undefined, ['Jerryc05']),
  new SoupDish('菠菜蛋汤', undefined, undefined, ['Jaybase']),
  new SoupDish('菠菜蛋汤', undefined, undefined, ['Jaybase']),
  new SoupDish('菠菜豆腐汤', undefined, undefined, ['Jaybase']),
  new SoupDish('韩式大酱汤', undefined, undefined, ['Jaybase']),
  new SoupDish('韩式辣海鲜汤', undefined, undefined, ['Jaybase']),
  new SoupDish('韩式辣豆腐汤', undefined, undefined, ['Jaybase']),
  new SoupDish('冬瓜排骨汤', undefined, undefined, ['Jaybase']),
  new SoupDish('关东煮', undefined, undefined, []),
  new SoupDish('萝卜大骨汤', undefined, undefined, []),
  new SoupDish('萝卜炖牛腩', undefined, undefined, []),
  new SoupDish('肉末蛋羹', undefined, undefined, ['Jerryc05']),
  new SoupDish('猪肚鸡', undefined, undefined, ['Jerryc05']),
  new SoupDish('蟹黄豆腐煲', undefined, undefined, ['Jerryc05']),
  new SoupDish('英式蛤蜊浓汤', undefined, undefined, ['Jerryc05']),
  new SoupDish('番茄虾滑汤', undefined, undefined, ['Jerryc05']),
  new SoupDish('文思豆腐', undefined, undefined, ['Jerryc05']),
  new StreetFoodDish('豆腐脑', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('卤煮', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('章鱼小丸子', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('大阪烧', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('麻辣香锅', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('麻辣烫', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('麻辣拌', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('铁板烧', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('烧烤', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('韩国烤肉', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('串串香', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('石锅拌饭', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('爆肚', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('鸭血粉丝汤', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('千层饼', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('寿司', undefined, undefined, ['Jaybase', 'Jerryc05']),
  new StreetFoodDish('千层蛋糕', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('半熟芝士条', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('鸭舌', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('鸭脖', undefined, undefined, ['Jaybase']),
  new StreetFoodDish('鸡汁土豆泥', undefined, undefined, ['Jerryc05']),
  new StreetFoodDish('铁板豆腐', undefined, undefined, ['Jerryc05']),
  new Drink('芝芝莓莓', undefined, undefined, ['Jerryc05']),
  new Drink('草莓牛乳茶', undefined, undefined, ['Jerryc05']),
  new DessertCake('草莓雪山蛋糕', undefined, undefined, ['Jerryc05']),
  new DessertCake('抹茶慕斯蛋糕', undefined, undefined, ['Jerryc05']),
]
