import {
  BeefDish, ChickenDish, ColdDish, CongeeDish, Dessert, DessertCake, Drink, Item, LambDish,
  NoodleDish, PorkDish, RiceDish, SeafoodDish, SoupDish, StreetFoodDish, VegetableDish, WheatenDish
} from './menu_types'
import {
  BeefShank, Chicken, ChickenFeet, Corn, Cucumber, Egg, Goji, Jellyfish, Lemon, Millet,
  MungBean, Mushroom, Peanut, Pork, Potato, PotherbMustard, PreservedEgg, Sesame, Shrimp, WoodEar
} from './ingredients'

export const menu: ReadonlyArray<Item> = [
  new CongeeDish('香菇鸡肉粥', 'Congee w/ Chicken & Mushrooms', [Chicken, Mushroom], ['Jaybase']),
  new CongeeDish(
    '皮蛋瘦肉粥', 'Congee w/ Pork & Preserved Eggs', [Pork, PreservedEgg], ['Jaybase', 'Jerryc05']
  ),
  new CongeeDish(
    '雪菜肉丝粥', 'Congee w/ potherb mustard & shredded pork', [PotherbMustard, Pork], ['Jaybase']
  ),
  new CongeeDish('八宝粥', 'Mixed Congee', null, ['Jaybase']),
  new CongeeDish('玉米碴子粥', 'Congee w/ Crushed Corn', [Corn, Goji], ['Jaybase']),
  new CongeeDish('小米粥', 'Millet Congee', [Millet, Goji], ['Jaybase']),
  new CongeeDish('白米粥', 'Rice Congee', [], ['Jaybase', 'Jerryc05']),
  new ColdDish('凉拌海蜇头', 'Jellyfish Head Salad', [Jellyfish], ['Jaybase', 'Jerryc05']),
  new ColdDish('凉拌黄瓜', 'Cucumber Salad', [Cucumber], ['Jaybase']),
  new ColdDish('拍黄瓜', 'Smashed Cucumber Salad', [Cucumber], ['Jaybase']),
  new ColdDish('油炸花生米', 'Fried Peanuts', [Peanut], ['Jaybase']),
  new ColdDish('五香牛肉', 'Multi Spiced Beef', [BeefShank], ['Jaybase']),
  new ColdDish('酱牛肉', 'Spiced Beef', [BeefShank], ['Jaybase', 'Jerryc05', 'Titi', 'Tuge']),
  new ColdDish('卤蛋', 'Marinated Egg', [Egg], ['Jaybase']),
  new ColdDish('酸辣虾', 'Sour & Spicy Shrimp', [Shrimp], ['Jaybase', 'Titi']),
  new ColdDish('泰式柠檬虾', null, null, ['Titi']),
  new ColdDish(
    '酸辣无骨鸡爪', 'Sour & Spicy Chicken Feet',
    [ChickenFeet, Lemon], ['Jaybase', 'Jerryc05', 'Titi', 'Wuge']
  ),
  new ColdDish('凉拌土豆丝', 'Shredded Potato Salad', [Potato], ['Jaybase']),
  new ColdDish('酸辣土豆丝', 'Sour & Spicy Shredded Potato', [Potato], ['Jaybase']),
  new ColdDish('白糖西红柿', 'Sour & Spicy Shredded Potato', [Potato], ['Jaybase']),
  new ColdDish('凉拌木耳', 'Wood Ear Salad', [WoodEar], ['Jaybase']),
  new ColdDish('五彩拉皮', 'Wood Ear Salad', [WoodEar], ['Jerryc05']),
  new WheatenDish('馅饼（自选）', 'Pie (Customized Filling)', [], ['Jaybase']),
  new WheatenDish('油条', 'Fried Dough Fritter', [], ['Jaybase']),
  new WheatenDish('葱油饼', 'Scallion Crepe', [], ['Jaybase']),
  new WheatenDish('农家酱香饼', 'Soy Flavored Flatbread Crepe', [], ['Jaybase']),
  new WheatenDish('鸡蛋饼', 'Egg Crepe', [Egg], ['Jaybase', 'Jerryc05']),
  new WheatenDish('春饼', 'Spring Crepe', [], ['Jaybase']),
  new WheatenDish('麻酱红糖饼', 'Brown Sugar Crepe w/ Sesame Paste', [Sesame], ['Jaybase']),
  new WheatenDish('煎饺', 'Fried Dumpling', [], ['Jaybase']),
  new WheatenDish('水饺', 'Dumpling', [], ['Jaybase']),
  new WheatenDish('红油抄手', 'Spicy Wonton in Chili Oil', null, ['Jaybase']),
  new WheatenDish('云吞', 'Wonton', null, ['Jaybase']),
  new WheatenDish('韭菜盒子', 'Fried Chinese Chives Pocket', null, ['Jaybase']),
  new WheatenDish('海鲜煎饼', null, null, ['Jaybase', 'Jerryc05']),
  new WheatenDish('蚵仔煎', 'Oyster Omelette', null, []),
  new NoodleDish('香菇鸡肉面', null, null, ['Jaybase']),
  new NoodleDish('红烧牛肉面', null, null, ['Jaybase', 'Jerryc05', 'Tuge', 'Titi']),
  new NoodleDish('排骨卤肉面', null, null, ['Jerryc05', 'Tuge']),
  new NoodleDish('重庆小面', null, null, ['Jaybase']),
  new NoodleDish('榨菜肉丝面', null, null, ['Jaybase']),
  new NoodleDish('雪菜肉丝面', null, null, ['Jaybase']),
  new NoodleDish('鸡汤面', null, null, ['Jaybase']),
  new NoodleDish('麻酱拌面', null, null, ['Jaybase']),
  new NoodleDish('鸡丝凉面', null, null, ['Jaybase']),
  new NoodleDish('大排面', null, null, ['Jaybase']),
  new NoodleDish('炒面', null, null, ['Jaybase']),
  new NoodleDish('炸酱面', null, null, ['Jaybase']),
  new NoodleDish('打卤面', null, null, ['Jaybase']),
  new NoodleDish('番茄鸡蛋面', null, null, ['Jaybase']),
  new NoodleDish('什锦面', null, null, ['Jaybase']),
  new NoodleDish('芸豆焖面', null, null, ['Jaybase']),
  new NoodleDish('意大利肉酱面', null, null, ['Jaybase']),
  new NoodleDish('中式肉酱面', null, null, ['Jaybase', 'Jerryc05', 'Titi']),
  new NoodleDish('番茄肥牛面', null, null, ['Jaybase']),
  new NoodleDish('阳春面', null, null, ['Jaybase']),
  new NoodleDish('油泼面', null, null, ['Jaybase']),
  new NoodleDish('冷面', null, null, ['Jaybase']),
  new NoodleDish('烤冷面', null, null, ['Jaybase']),
  new NoodleDish('日本拉面', null, null, ['Jaybase']),
  new NoodleDish('虾仁奶油意面', null, null, ['Jerryc05']),
  new NoodleDish('番茄肉酱意面', null, null, ['Jerryc05', 'Titi']),
  new NoodleDish('青椒牛柳意面', null, null, ['Jerryc05', 'Titi']),
  new RiceDish('卤肉饭', null, null, ['Jaybase']),
  new RiceDish('照烧鸡肉饭', null, null, ['Jaybase']),
  new RiceDish('照烧牛肉饭', null, null, ['Jaybase']),
  new RiceDish('蛋炒饭', null, null, ['Jaybase']),
  new RiceDish('盖浇饭', null, null, ['Jaybase']),
  new RiceDish('煲仔饭', null, null, ['Jaybase']),
  new RiceDish('小龙虾盖饭', null, null, ['Jaybase']),
  new RiceDish('日式牛丼饭', null, null, []),
  new RiceDish('日式滑蛋猪排饭', null, null, ['Jerryc05']),
  new RiceDish('茄汁芝士焗饭', null, null, ['Jerryc05']),
  new RiceDish('海鲜糯米鸡', null, null, ['Jerryc05']),
  new RiceDish('三角烤饭团', null, null, ['Jerryc05']),
  new RiceDish('午餐肉烤饭团', null, null, ['Jerryc05']),
  new RiceDish('卤猪脚饭', null, null, ['Jerryc05']),
  new RiceDish('猪油拌饭', null, null, ['Jerryc05']),
  new RiceDish('韩式拌饭', null, null, ['Jerryc05']),
  new PorkDish('小酥肉', null, null, ['Jaybase', 'Jerryc05']),
  new PorkDish('干炸里脊', null, null, ['Jaybase']),
  new PorkDish('糖醋里脊', null, null, ['Jaybase']),
  new PorkDish('锅包肉', null, null, ['Jaybase']),
  new PorkDish('溜肉段', null, null, ['Jaybase']),
  new PorkDish('芸豆土豆炖排骨', null, null, ['Jaybase']),
  new PorkDish('糖醋排骨', null, null, ['Jaybase']),
  new PorkDish('豆豉排骨', null, null, ['Jaybase']),
  new PorkDish('酱排骨', null, null, ['Jerryc05']),
  new PorkDish('避风塘排骨', null, null, ['Jaybase']),
  new PorkDish('蒜香排骨', null, null, ['Jaybase', 'Jerryc05']),
  new PorkDish('腐乳排骨', null, null, []),
  new PorkDish('鱼香肉丝', null, null, ['Jaybase']),
  new PorkDish('京酱肉丝', null, null, ['Jaybase', 'Jerryc05']),
  new PorkDish('青椒肉丝', null, null, ['Jaybase']),
  new PorkDish('水煮肉片', null, null, ['Jaybase']),
  new PorkDish('木须肉', null, null, ['Jaybase']),
  new PorkDish('洋葱炒肉', null, null, ['Jaybase']),
  new PorkDish('红烧肉', null, null, ['Jaybase']),
  new PorkDish('梅菜扣肉', null, null, ['Jerryc05']),
  new PorkDish('韩式辣白菜炒肉', null, null, ['Jaybase']),
  new PorkDish('烤猪蹄', null, null, ['Jaybase']),
  new PorkDish('炸猪蹄', null, null, ['Jaybase']),
  new PorkDish('红烧猪蹄', null, null, ['Jaybase', 'Jerryc05']),
  new PorkDish('黄豆焖猪蹄', null, null, []),
  new PorkDish('酱猪肘', null, null, ['Jerryc05']),
  new PorkDish('烤猪肉串', null, null, ['Jaybase']),
  new PorkDish('烤五花肉', null, null, ['Jaybase']),
  new PorkDish('咖喱猪排饭', null, null, ['Jaybase']),
  new PorkDish('红烧狮子头', null, null, ['Jaybase']),
  new PorkDish('蒸排骨', null, null, []),
  new PorkDish('豆瓣炖排骨', null, null, []),
  new PorkDish('肉末麻婆豆腐', null, null, ['Jerryc05']),
  new PorkDish('辣椒炒肉', null, null, ['Jerryc05']),
  new PorkDish('脆皮猪五花', null, null, []),
  new PorkDish('回锅肉', null, null, ['Jerryc05']),
  new PorkDish('粉蒸肉', null, null, ['Jerryc05']),
  new PorkDish('粉蒸排骨', null, null, ['Jerryc05']),
  new PorkDish('照烧猪肉', null, null, ['Jerryc05']),
  new PorkDish('虎纠荔枝肉', null, null, ['Jerryc05']),
  new PorkDish('水煮肉片', null, null, ['Jerryc05']),
  new BeefDish('孜然牛肉', null, null, ['Jaybase']),
  new BeefDish('葱爆牛肉', null, null, ['Jaybase']),
  new BeefDish('酸汤肥牛', null, null, ['Jaybase']),
  new BeefDish('肥牛金针菇卷', null, null, ['Jaybase']),
  new BeefDish('煎牛排', null, null, ['Jaybase', 'Jerryc05', 'Tuge']),
  new BeefDish('烤牛排', null, null, ['Jaybase']),
  new BeefDish('烤牛肉串', null, null, ['Jaybase']),
  new BeefDish('红烧牛腩', null, null, ['Jerryc05']),
  new BeefDish('番茄牛腩', null, null, ['Jaybase']),
  new BeefDish('土豆烧牛腩', null, null, []),
  new BeefDish('咖喱牛肉', null, null, ['Jaybase']),
  new BeefDish('黑椒牛仔骨', null, null, ['Jaybase', 'Jerryc05']),
  new BeefDish('杭椒牛柳', null, null, ['Jaybase']),
  new BeefDish('香菜炒牛百叶', null, null, ['Jaybase']),
  new BeefDish('黑椒牛肉粒', null, null, ['Jaybase']),
  new BeefDish('香菜拌牛肉', null, null, ['Jerryc05']),
  new LambDish('孜然羊肉', null, null, ['Jaybase']),
  new LambDish('葱爆羊肉', null, null, ['Jaybase']),
  new LambDish('麻酱拌肥羊', null, null, ['Jaybase']),
  new LambDish('羊蝎子', null, null, ['Jaybase']),
  new LambDish('烤羊肉串', null, null, ['Jaybase', 'Jerryc05']),
  new LambDish('鱼羊鲜', null, null, []),
  new LambDish('法式香煎小羊排', null, null, ['Jerryc05']),
  new ChickenDish('大盘鸡', null, null, ['Jaybase']),
  new ChickenDish('口水鸡', null, null, ['Jaybase']),
  new ChickenDish('炸鸡', null, null, ['Jaybase']),
  new ChickenDish('盐酥鸡', null, null, ['Jaybase', 'Jerryc05']),
  new ChickenDish('鸡米花', null, null, ['Jaybase']),
  new ChickenDish('可乐鸡翅', null, null, ['Jaybase', 'Jerryc05', 'Tuge']),
  new ChickenDish('红烧鸡翅', null, null, ['Jaybase', 'Jerryc05', 'Tuge']),
  new ChickenDish('蒜香鸡翅', null, null, ['Jaybase']),
  new ChickenDish('橙香鸡翅', null, null, []),
  new ChickenDish('奥尔良鸡翅', null, null, []),
  new ChickenDish('小鸡炖蘑菇', null, null, ['Jaybase']),
  new ChickenDish('地锅鸡', null, null, ['Jaybase']),
  new ChickenDish('烤鸡', null, null, ['Jaybase', 'Jerryc05', 'Titi', 'Wuge']),
  new ChickenDish('照烧鸡', null, null, ['Jaybase']),
  new ChickenDish('杏鲍菇炒鸡丁', null, null, ['Jaybase']),
  new ChickenDish('辣子鸡', null, null, ['Jaybase']),
  new ChickenDish('宫保鸡丁', null, null, ['Jaybase']),
  new ChickenDish('咖喱鸡', null, null, ['Jaybase', 'Jerryc05']),
  new ChickenDish('炸鸡排', null, null, ['Jaybase']),
  new ChickenDish('爆浆鸡排', null, null, ['Jaybase']),
  new ChickenDish('炸鸡柳', null, null, ['Jaybase']),
  new ChickenDish('烤鸡胸', null, null, ['Jaybase']),
  new ChickenDish('黄焖鸡', null, null, ['Jerryc05', 'Tuge']),
  new ChickenDish('宫保鸡丁', null, null, ['Jerryc05', 'Tuge']),
  new SeafoodDish('红烧带鱼', null, null, ['Jaybase']),
  new SeafoodDish('炸带鱼', null, null, ['Jaybase']),
  new SeafoodDish('红烧鱼', null, null, ['Jaybase', 'Jerryc05']),
  new SeafoodDish('松鼠桂鱼', null, null, ['Jaybase']),
  new SeafoodDish('烤鱼', null, null, ['Jaybase']),
  new SeafoodDish('红烧鲅鱼', null, null, ['Jaybase']),
  new SeafoodDish('地锅鱼', null, null, ['Jaybase']),
  new SeafoodDish('蒜蓉大虾', null, null, ['Jaybase']),
  new SeafoodDish('干烧大虾', null, null, ['Jaybase']),
  new SeafoodDish('凤尾大虾', null, null, ['Jaybase']),
  new SeafoodDish('油焖大虾', null, null, ['Jaybase', 'Jerryc05', 'Tuge', 'Wuge']),
  new SeafoodDish('葱烧海参', null, null, ['Jaybase']),
  new SeafoodDish('肉末海参', null, null, ['Jaybase']),
  new SeafoodDish('蒜蓉小海鲜', null, null, ['Jaybase']),
  new SeafoodDish('麻辣小龙虾', null, null, ['Jaybase']),
  new SeafoodDish('水煮海鲜', null, null, ['Jaybase']),
  new SeafoodDish('香辣蟹', null, null, ['Jaybase']),
  new SeafoodDish('辣炒蛤蜊', null, null, ['Jaybase']),
  new SeafoodDish('凉拌八爪鱼', null, null, ['Jaybase']),
  new SeafoodDish('铁板鱿鱼', null, null, ['Jaybase']),
  new SeafoodDish('清蒸鲈鱼', null, null, ['Jaybase', 'Jerryc05']),
  new SeafoodDish('西兰花炒虾仁', null, null, ['Jaybase']),
  new SeafoodDish('蒜蓉扇贝', null, null, ['Jaybase']),
  new SeafoodDish('红酒香煎三文鱼', null, null, ['Jerryc05']),
  new SeafoodDish('珍珠丸子', null, null, ['Jerryc05']),
  new SeafoodDish('麻辣香锅', null, null, ['Jerryc05', 'Tuge']),
  new SeafoodDish('鱼头泡饼', null, null, ['Jerryc05']),
  new SeafoodDish('黄油芝士虾', null, null, ['Jerryc05']),
  new SeafoodDish('炸虾天妇罗', null, null, ['Jerryc05']),
  new VegetableDish('醋溜白菜', null, null, ['Jaybase']),
  new VegetableDish('醋溜土豆丝', null, null, ['Jaybase']),
  new VegetableDish('酸辣土豆丝', null, null, ['Jaybase']),
  new VegetableDish('蒜蓉青菜', null, null, ['Jaybase']),
  new VegetableDish('上汤娃娃菜', null, null, ['Jaybase']),
  new VegetableDish('番茄炒鸡蛋', null, null, ['Jaybase']),
  new VegetableDish('冬瓜虾仁', null, null, ['Jaybase']),
  new VegetableDish('萝卜大虾', null, null, ['Jaybase']),
  new VegetableDish('茄盒', null, null, ['Jaybase']),
  new VegetableDish('藕盒', null, null, ['Jaybase']),
  new VegetableDish('肉末茄子', null, null, ['Jaybase']),
  new VegetableDish('鱼香茄子', null, null, ['Jaybase']),
  new VegetableDish('拔丝地瓜', null, null, ['Jaybase']),
  new VegetableDish('干煸豆角', null, null, ['Jaybase']),
  new VegetableDish('干煸大头菜', null, null, ['Jaybase']),
  new VegetableDish('蚝油生菜', null, null, ['Jaybase']),
  new VegetableDish('豆豉鲮鱼油麦菜', null, null, ['Jaybase']),
  new VegetableDish('干锅花菜', null, null, ['Jaybase']),
  new VegetableDish('干锅豆角', null, null, ['Jaybase']),
  new VegetableDish('干锅土豆片', null, null, ['Jaybase']),
  new VegetableDish('干锅豆腐', null, null, ['Jaybase']),
  new VegetableDish('包菜鱿鱼粉丝煲', null, null, ['Jerryc05']),
  new VegetableDish('蒜蓉西兰花', null, null, ['Jerryc05']),
  new VegetableDish('韭菜炒蛋', null, null, ['Jerryc05']),
  new VegetableDish('芹菜炒肉末', null, null, []),
  new VegetableDish('炒合菜', null, null, []),
  new VegetableDish('洋葱炒蛋', null, null, []),
  new VegetableDish('皮蛋擂青椒', null, null, ['Jerryc05']),
  new VegetableDish('素三鲜', null, null, ['Jerryc05']),
  new VegetableDish('龙吟鸡腿', null, null, ['Jerryc05']),
  new SoupDish('绿豆汤', 'Mung Bean Soup', [MungBean], ['Jaybase']),
  new SoupDish('紫菜蛋汤', null, null, ['Jaybase']),
  new SoupDish('番茄鸡蛋汤', null, null, ['Jaybase']),
  new SoupDish('排骨汤', null, null, ['Jaybase']),
  new SoupDish('鸡汤', null, null, ['Jaybase']),
  new SoupDish('清炖羊肉汤', null, null, ['Jaybase']),
  new SoupDish('鱼汤', null, null, ['Jaybase']),
  new SoupDish('番茄牛腩汤', null, null, ['Jaybase']),
  new SoupDish('牛尾汤', null, null, ['Jaybase']),
  new SoupDish('猪脚汤', null, null, ['Jaybase']),
  new SoupDish('鸡蛋蘑菇汤', null, null, ['Jaybase']),
  new SoupDish('平桥豆腐羹', null, null, ['Jaybase']),
  new SoupDish('西湖牛肉羹', null, null, ['Jerryc05']),
  new SoupDish('宋嫂鱼羹', null, null, ['Jerryc05']),
  new SoupDish('菠菜蛋汤', null, null, ['Jaybase']),
  new SoupDish('菠菜蛋汤', null, null, ['Jaybase']),
  new SoupDish('菠菜豆腐汤', null, null, ['Jaybase']),
  new SoupDish('韩式大酱汤', null, null, ['Jaybase']),
  new SoupDish('韩式辣海鲜汤', null, null, ['Jaybase']),
  new SoupDish('韩式辣豆腐汤', null, null, ['Jaybase']),
  new SoupDish('冬瓜排骨汤', null, null, ['Jaybase']),
  new SoupDish('关东煮', null, null, []),
  new SoupDish('萝卜大骨汤', null, null, []),
  new SoupDish('萝卜炖牛腩', null, null, []),
  new SoupDish('肉末蛋羹', null, null, ['Jerryc05']),
  new SoupDish('猪肚鸡', null, null, ['Jerryc05']),
  new SoupDish('蟹黄豆腐煲', null, null, ['Jerryc05']),
  new SoupDish('英式蛤蜊浓汤', null, null, ['Jerryc05']),
  new SoupDish('番茄虾滑汤', null, null, ['Jerryc05']),
  new SoupDish('文思豆腐', null, null, ['Jerryc05']),
  new StreetFoodDish('豆腐脑', null, null, ['Jaybase']),
  new StreetFoodDish('卤煮', null, null, ['Jaybase']),
  new StreetFoodDish('章鱼小丸子', null, null, ['Jaybase']),
  new StreetFoodDish('大阪烧', null, null, ['Jaybase']),
  new StreetFoodDish('麻辣香锅', null, null, ['Jaybase']),
  new StreetFoodDish('麻辣烫', null, null, ['Jaybase']),
  new StreetFoodDish('麻辣拌', null, null, ['Jaybase']),
  new StreetFoodDish('铁板烧', null, null, ['Jaybase']),
  new StreetFoodDish('烧烤', null, null, ['Jaybase']),
  new StreetFoodDish('韩国烤肉', null, null, ['Jaybase']),
  new StreetFoodDish('串串香', null, null, ['Jaybase']),
  new StreetFoodDish('石锅拌饭', null, null, ['Jaybase']),
  new StreetFoodDish('爆肚', null, null, ['Jaybase']),
  new StreetFoodDish('鸭血粉丝汤', null, null, ['Jaybase']),
  new StreetFoodDish('千层饼', null, null, ['Jaybase']),
  new StreetFoodDish('寿司', null, null, ['Jaybase', 'Jerryc05']),
  new StreetFoodDish('千层蛋糕', null, null, ['Jaybase']),
  new StreetFoodDish('半熟芝士条', null, null, ['Jaybase']),
  new StreetFoodDish('鸭舌', null, null, ['Jaybase']),
  new StreetFoodDish('鸭脖', null, null, ['Jaybase']),
  new StreetFoodDish('鸡汁土豆泥', null, null, ['Jerryc05']),
  new StreetFoodDish('铁板豆腐', null, null, ['Jerryc05']),
  new StreetFoodDish('手工凉皮', null, null, ['Titi']),
  new Drink('芝芝莓莓', null, null, ['Jerryc05']),
  new Drink('草莓牛乳茶', null, null, ['Jerryc05']),
  new Drink('满杯葡萄', null, null, ['Titi']),
  new Drink('芒果冰沙', null, null, ['Titi']),
  new Drink('杨枝甘露', null, null, ['Titi']),
  new Drink('芝芝桃桃', null, null, ['Titi']),
  new Drink('棒打鲜橙', null, null, []),
  new Drink('西瓜啵啵', null, null, []),
  new Drink('声声乌龙', null, null, []),
  new Drink('生椰拿铁', null, null, []),
  new Drink('薄荷拿铁', null, null, []),
  new Drink('茶冻撞奶', null, null, []),
  new Drink('草莓大福', null, null, []),
  new Drink('红茶玛奇朵', null, null, []),
  new Drink('芝芝椰椰', null, null, []),
  new Drink('芝芝芒芒', null, null, []),
  new Drink('芝芝西瓜', null, null, []),
  new Drink('桃桃优格', null, null, []),
  new Drink('葡萄多多', null, null, []),
  new Drink('菠萝多多', null, null, []),
  new Drink('西柚多多', null, null, []),
  new Drink('满杯西柚', null, null, []),
  new Dessert('蛋挞', null, null, ['Wuge']),
  new Dessert('芒果小丸子', null, null, ['Jaybase']),
  new DessertCake('草莓雪山蛋糕', null, null, ['Jerryc05']),
  new DessertCake('抹茶慕斯蛋糕', null, null, ['Jerryc05']),
  new DessertCake('玫瑰荔枝蛋糕', null, null, ['Titi']),
]
