export const bgBigOColor = 'bg-[#ab641b]'
export const darkBgBigOColor = 'dark:bg-[#ab641b]'
export const textBigOColor = 'text-[#ab641b]'
export const darkTextBigOColor = 'dark:text-[#ab641b]'
export const bgMtColor = 'bg-[#3e2d14]'
export const darkBgMtColor = 'dark:bg-[#3e2d14]'
export const textMtColor = 'text-[#3e2d14]'
export const darkTextMtColor = 'dark:text-[#3e2d14]'
